### ISSUE TITLE
onchange event doesn't fire

### ISSUE THREAD

**Issue by dfoverdx** [WebCoder49/code-input#28]
As near as I can tell, onchange doesn't *ever* fire.

```lang-html
<code-input lang="js" onchange="console.log(this.value)"></code-input>
```

The `console.log` never occurs.  I stepped through the code and found one issue (line 71), but even when I fixed it, I didn't get any change events.  AFAIK, changing the value via javascript doesn't trigger change events on any element, so you'd need to manually dispatch them.

**Comment by dfoverdx** [comment]
Never mind.  It does seem to be triggering static text values, but not when you use `.addEventListener` to the `<code-input>` element.  My workaround (in React) was to use `useRef()` and `useEffect()` to attach the eventListener to the textarea's change event.

**Comment by WebCoder49** [comment]
The pull request above should fix this.

**Comment by WebCoder49** [comment]
1. @arohman84 I think you're running the addEventListener function on the codeInput.CodeInput class rather than a specific element. What you need to do is get a specific code-input element in JavaScript (with [document.querySelector with a CSS selector](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector), for example) then run (with that code-input element in the `myCodeInputElement` variable) `myCodeInputElement.addEventListener('change', (evt) => console.log(myCodeInputElement))`. 
2. You'll see that I changed your code slightly above. This is because the "val" parameter you are using will actually contain the [change event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/change_event) object.
3. If you keep having problems, please make sure you are using version 2.1.0 of the library.

I've put this all in a [small demo here](https://codepen.io/WebCoder49/pen/zYbejmW?editors=1111). If you have any questions / suggestions for this library, please feel free to let me know!
