### ISSUE TITLE
Issue with ENTER key and left over marked block...

### ISSUE THREAD

**Issue by AzzaAzza69** [WebCoder49/code-input#35]
When lines are marked up, the ENTER key deletes the text but block marks up any text that follows.

steps to reproduce:
  mark up the word block in this sentence and press enter, you will get a new line but " in t" will still be marked up as opposed to expected behaviour of new line and cursor in front of " in this...".

**Comment by WebCoder49** [comment]
Thank you for pointing this out and the many other contributions you have made via issues. I am afraid that I may not be able to address this until late June due to being very busy at the moment, but will try to address it ASAP.

**I have one question: are you using the `indent` plugin? If so, this line could be changed to replace `selection_end` with `selection_start`.**
https://github.com/WebCoder49/code-input/blob/d88a382f9fc78bb0faf850b375ce4b83ace98678/plugins/indent.js#L138

Once you confirm, I will amend this and test it as soon as I have time.

**Comment by AzzaAzza69** [comment]
I haven't downloaded the latest version, I only tried out the online demo @ https://codepen.io/WebCoder49/details/jOypJOx

**Comment by WebCoder49** [comment]
Yes, that does use the `indent` plugin. Thank you for the quick reply.
