### ISSUE TITLE
Setting language to HTML makes highlighting stop working

### ISSUE THREAD

**Issue by vcdomith** [WebCoder49/code-input#64]
I'm not sure if this is an issue with the code-input element in itself or with hljs library. What I noticed is when I either select html as the highlighted language or when I simply create the code-input with the default lang as html the highlighting stops, even though the language is updated with the console.logs and no errors or exceptions are raised. I implemented the code-input with the HLJS template, not sure if this is a problem with Prism.

I'll include a link to the web app I'm using this element in case anyone wants to replicate (the default lang is python):
[https://vcdomith.github.io/aluradev/](url)

**Comment by WebCoder49** [comment]
That's weird - I never saw that before. Your site works fine for me right now on Microsoft Edge (Chromium) version 118.0.2088.69 (Official build) (64-bit) on Windows 11. What browser/operating system are you using - maybe the problem is browser-specific?

![image](https://github.com/WebCoder49/code-input/assets/69071853/54220954-272f-4e98-9224-6e19f56f704e)

**Comment by vcdomith** [comment]
I was testing it on chrome, mosr recent build. I'll try it in another browser and write you back

**Comment by WebCoder49** [comment]
Thank you for this. I feel it may have been an issue unique to the version of your code as now you have added another commit and the language selector no longer seems to work. I will clone your project when I have time (I am quite busy right now) and see if I can help identify the bug.
