### ISSUE TITLE
language attr and classes set to "none" in all cases

### ISSUE THREAD

**Issue by Devastatia** [WebCoder49/code-input#96]
The language attribute is ignored regardless of what I set it to ("HTML", "html", "CSS", etc.)

code-input.language is set to "none"

pre and code classes both set to "language-none"

The attached screenshot tells all.

![code-input-screenshot](https://github.com/WebCoder49/code-input/assets/130798278/2915f20a-c557-48e6-9108-8cdee6c2d6b8)

**Comment by Devastatia** [comment]
Curiously, it works as expected when Prism is replaced with highlight.js.

**Comment by WebCoder49** [comment]
## Quick Workaround ([code-input demo](https://codepen.io/WebCoder49/pen/BaeaeLE))
The bug should disappear if you add `language="none"` as an HTML attribute in the markup of the code-input element (or via JavaScript to the code-input element as soon as it is created).

---
## Properly Fixing
There seems to be a problem with these lines of code:

https://github.com/WebCoder49/code-input/blob/main/code-input.js#L760-L764

I'm afraid I'm quite busy right now but the bug's scope being restricted to Prism suggests it might be due to Prism's functionality of adding the `language-none` class, which is not part of highlight.js. I will be available shortly after 25 May and will look at this bug more then.

Clearly, if you know how to fix it, comments / a pull request are very welcome, but not required.
